--  Queries to analyze nessas pet care service database to see how the business is doing so far

USE nessaspetcareservices;


--  Total # of appointments since business has opened?

SELECT COUNT(Appointment_ID) AS Total_Appointments
FROM Appointments;

--  Total # of appointments broken down by month to see how opening month of September went and how this month is going so far

SELECT MONTH(Appointment_Date) AS Month, COUNT(Appointment_ID) AS Total_Appointments
FROM appointments
WHERE Appointment_Date BETWEEN '2024-09-01' AND '2024-10-19'
GROUP BY MONTH(Appointment_Date);

	# Business is showing consistency and october is on track to surpassing sept appointments, correlating with the google trend data set. 
    
-- What's the most frequently used service category by counting the appointments for each category? 

SELECT Category, COUNT(Appointment_ID) AS Total_Appointments
FROM appointments
JOIN services USING (Service_ID)
GROUP BY Category
ORDER BY Total_Appointments DESC;

	# So far grooming is bringing in more pets, fitting the google trend of high grooming request in this quarter. Need to market the walkings, maybe specials/discounts?
    
# What's the revenue so far generated by each service?

SELECT Service_Name, SUM(Price) AS Total_Revenue
FROM appointments
JOIN Services USING (Service_ID)
GROUP BY Service_Name
ORDER BY Total_Revenue DESC;

	# Although we saw more grooming appointments than boarding, boarding does bring in more revenue by appointment
    
